# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67fde8c06d924798d558c9b8b0eee8b20384c84f6beba5dbd35738b46bc301ced5e835d6560b9a0d65e432b176f506af3b8938d2ab197adbed7ba45994ca1213

test:
  secret_key_base: 540e3e71640158ca1f9cd21f2aa80a51b0318d633306e21e190f7fb680a26419dcf5568802c80bcc7adb5c78add8dd3f95f3946664683cbe1d5cb45931068da3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
